In [2]:
import numpy as np
import pandas as pd
titanic_df=pd.read_csv("titanic_df_Ageoutlier.csv")

In [3]:
titanic_df.head()

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
##data Encoding
#Nominal and Ordinal data

In [5]:
### Nominal Data-> data without natural orded
titanic_df.Gender

0        male
1      female
2      female
3      female
4        male
        ...
709    female
710      male
711    female
712      male
713      male
Name: Gender, Length: 714, dtype: str

One _Hot Encoding

In [6]:
#pandas
pd.get_dummies(titanic_df,columns=["Gender","Embarked"], dtype=int).head()

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S
0,0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1

In [7]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder(sparse_output=False)

In [9]:
one_hot_encoder.fit_transform(
    titanic_df[["Gender","Embarked"]]
)

array([[0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.]], shape=(714, 6))

In [11]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object),
 array(['C', 'Q', 'S', nan], dtype=object)]

In [12]:
#Ordinal Data
titanic_df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
709    Q
710    S
711    S
712    C
713    Q
Name: Embarked, Length: 714, dtype: str

In [14]:
#pandas
titanic_df["encoded_embarked"],rule=titanic_df.Embarked.factorize(sort=True)

In [15]:
titanic_df.head()

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2

In [16]:
rule

Index(['C', 'Q', 'S'], dtype='str')

In [17]:
titanic_df.encoded_embarked.value_counts()

encoded_embarked
 2    554
 0    130
 1     28
-1      2
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

In [19]:
ordinal_encoder=OrdinalEncoder()

In [21]:
encoded_result=ordinal_encoder.fit_transform(titanic_df[["Embarked"]])

In [22]:
ordinal_encoder.categories_

[array(['C', 'Q', 'S', nan], dtype=object)]

In [23]:
ordinal_encoder.inverse_transform(
    [[1],[2],[0],[1]]
)

array([['Q'],
       ['S'],
       ['C'],
       ['Q']], dtype=object)

In [25]:
titanic_df.head(2)

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0

In [26]:
final_df=titanic_df.drop(["Name","Ticket","encoded_embarked"],axis=1)

In [27]:
final_df.head()

,Unnamed: 0,PassengerId,Survived,PStatus,Gender,Age,SibSp,Parch,Fare,Cabin,Embarked
0,0,1,0,3,male,22.0,1,0,7.2500,NaN,S
1,1,2,1,1,female,38.0,1,0,71.2833,C85,C
2,2,3,1,3,female,26.0,0,0,7.9250,NaN,S
3,3,4,1,1,female,35.0,1,0,53.1000,C123,S
4,4,5,0,3,male,35.0,0,0,8.0500,NaN,S

In [28]:
onehot_encoder=OneHotEncoder(sparse_output=False)
ordinal_encoder=OrdinalEncoder(dtype=int)

In [30]:
age_embarked_encoded=onehot_encoder.fit_transform(titanic_df[["Gender","Embarked"]])
pclass_encoded=ordinal_encoder.fit_transform(titanic_df[["PStatus"]])

In [34]:
final_df.Pclass=PStatus.encoded

NameError: name 'PStatus' is not defined

In [36]:
pd.get_dummies(final_df,columns=["Gender","Embarked"],dtype=int)

,Unnamed: 0,PassengerId,Survived,PStatus,Age,SibSp,Parch,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S
0,0,1,0,3,22.0,1,0,7.2500,NaN,0,1,0,0,1
1,1,2,1,1,38.0,1,0,71.2833,C85,1,0,1,0,0
2,2,3,1,3,26.0,0,0,7.9250,NaN,1,0,0,0,1
3,3,4,1,1,35.0,1,0,53.1000,C123,1,0,0,0,1
4,4,5,0,3,35.0,0,0,8.0500,NaN,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,885,886,0,3,39.0,0,5,29.1250,NaN,1,0,0,1,0
710,886,887,0,2,27.0,0,0,13.0000,NaN,0,1,0,0,1
711,887,888,1,1,19.0,0,0,30.0000,B42,1,0,0,0,1
712,889,890,1,1,26.0,0,0,30.0000,C148,0,1,1,0,0
713,890,891,0,3,32.0,0,0,7.7500,NaN,0,1,0,1,0

In [37]:
[a.flatten() for a in one_hot_encoder]

TypeError: 'OneHotEncoder' object is not iterable

In [38]:
final_df.to_csv("../final_titanic_dataset.csv", index=False)