In [1]:
import numpy as np
import pandas as pd
titanic_df=pd.read_csv("titanic_df_Ageoutlier.csv")

In [2]:
titanic_df.head()

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
##data Encoding
#Nominal and Ordinal data

In [4]:
### Nominal Data-> data without natural orded
titanic_df.Gender

0        male
1      female
2      female
3      female
4        male
        ...
709    female
710      male
711    female
712      male
713      male
Name: Gender, Length: 714, dtype: str

One _Hot Encoding

In [6]:
#pandas
pd.get_dummies(titanic_df,columns=["Gender","Embarked"], dtype=int).head()

,Unnamed: 0,PassengerId,Survived,PStatus,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S
0,0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1