In [62]:
import pandas as pd
df1=pd.DataFrame({
    "acc":[13,21,22,23],"name":["Ram","Sam","hari", "Krishna"],"age":[12,24,32,42]
})
df2=pd.DataFrame({
    "acc":[13,21,22,23],"principle":[500,55,550,600],"interest":[6.3,7.8,9.9,5.5]
})

In [63]:
df1

   acc     name  age
0   13      Ram   12
1   21      Sam   24
2   22     hari   32
3   23  Krishna   42

In [64]:
df2

   acc  principle  interest
0   13        500       6.3
1   21         55       7.8
2   22        550       9.9
3   23        600       5.5

In [65]:
pd.concat([df1,df2], axis=1)

   acc     name  age  acc  principle  interest
0   13      Ram   12   13        500       6.3
1   21      Sam   24   21         55       7.8
2   22     hari   32   22        550       9.9
3   23  Krishna   42   23        600       5.5

In [66]:
pd.concat([df1,df2], axis=0,ignore_index=True)

   acc     name   age  principle  interest
0   13      Ram  12.0        NaN       NaN
1   21      Sam  24.0        NaN       NaN
2   22     hari  32.0        NaN       NaN
3   23  Krishna  42.0        NaN       NaN
4   13      NaN   NaN      500.0       6.3
5   21      NaN   NaN       55.0       7.8
6   22      NaN   NaN      550.0       9.9
7   23      NaN   NaN      600.0       5.5

In [67]:
#Merging
df1, df2

(   acc     name  age
 0   13      Ram   12
 1   21      Sam   24
 2   22     hari   32
 3   23  Krishna   42,
    acc  principle  interest
 0   13        500       6.3
 1   21         55       7.8
 2   22        550       9.9
 3   23        600       5.5)

In [68]:
pd.merge(df1,df2,how="left",on='acc')

   acc     name  age  principle  interest
0   13      Ram   12        500       6.3
1   21      Sam   24         55       7.8
2   22     hari   32        550       9.9
3   23  Krishna   42        600       5.5

In [69]:
df1=pd.DataFrame({
    "acc":[13,20,22,23],"name":["Ram","Sam","hari", "Krishna"],"age":[12,24,32,42]
})
df2=pd.DataFrame({
    "acc":[13,21,22,23,25],"principle":[500,55,550,600,400],"interest":[6.3,7.8,9.9,5.5,2.5]
})

In [70]:
pd.merge(df1,df2,how="right",on='acc')

   acc     name   age  principle  interest
0   13      Ram  12.0        500       6.3
1   21      NaN   NaN         55       7.8
2   22     hari  32.0        550       9.9
3   23  Krishna  42.0        600       5.5
4   25      NaN   NaN        400       2.5

In [71]:
pd.merge(df1,df2,how="left",on='acc')

   acc     name  age  principle  interest
0   13      Ram   12      500.0       6.3
1   20      Sam   24        NaN       NaN
2   22     hari   32      550.0       9.9
3   23  Krishna   42      600.0       5.5

In [72]:
pd.merge(df1,df2,how="inner",on='acc',indicator=True)

   acc     name  age  principle  interest _merge
0   13      Ram   12        500       6.3   both
1   22     hari   32        550       9.9   both
2   23  Krishna   42        600       5.5   both

In [73]:
pd.merge(df1,df2,how="outer",on='acc',indicator=True)

   acc     name   age  principle  interest      _merge
0   13      Ram  12.0      500.0       6.3        both
1   20      Sam  24.0        NaN       NaN   left_only
2   21      NaN   NaN       55.0       7.8  right_only
3   22     hari  32.0      550.0       9.9        both
4   23  Krishna  42.0      600.0       5.5        both
5   25      NaN   NaN      400.0       2.5  right_only

In [74]:
pd.merge_ordered(df1,df2,how="inner",on='acc')

   acc     name  age  principle  interest
0   13      Ram   12        500       6.3
1   22     hari   32        550       9.9
2   23  Krishna   42        600       5.5

In [75]:
pd.merge_asof(df1,df2,on='acc')

   acc     name  age  principle  interest
0   13      Ram   12        500       6.3
1   20      Sam   24        500       6.3
2   22     hari   32        550       9.9
3   23  Krishna   42        600       5.5

In [76]:
df1.merge(df2)

   acc     name  age  principle  interest
0   13      Ram   12        500       6.3
1   22     hari   32        550       9.9
2   23  Krishna   42        600       5.5

In [77]:
#Joining-based on index
df1,df2

(   acc     name  age
 0   13      Ram   12
 1   20      Sam   24
 2   22     hari   32
 3   23  Krishna   42,
    acc  principle  interest
 0   13        500       6.3
 1   21         55       7.8
 2   22        550       9.9
 3   23        600       5.5
 4   25        400       2.5)

In [78]:
df1.set_index("acc", inplace=True)
print(df1)

        name  age
acc
13       Ram   12
20       Sam   24
22      hari   32
23   Krishna   42

In [79]:
df2.set_index("acc", inplace=True)
print(df2)

     principle  interest
acc
13         500       6.3
21          55       7.8
22         550       9.9
23         600       5.5
25         400       2.5

In [80]:
df1.join(df2,how="inner",lsuffix="_left")

        name  age  principle  interest
acc
13       Ram   12        500       6.3
22      hari   32        550       9.9
23   Krishna   42        600       5.5

In [81]:
stacked=df1.stack()
stacked

acc
13   name        Ram
     age          12
20   name        Sam
     age          24
22   name       hari
     age          32
23   name    Krishna
     age          42
dtype: object